spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/satishusk/spring-cloud-config.git
  security:
    user:
      name: admin
      password: admin

server:
  port: 8888

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always